config/routes.rb
Rails.application.routes.draw do

  get 'auctions_users/create'

  get 'auctions_users/destroy'

  get 'auctions/myauctions'

  resources :auctioneers

  resources :bids

  resources :items do
    member do
      get 'newbid'
    end
    resources :bids
    end 

  resources :auctions do
    member do
      get 'auction_items'
      get 'finalize'
    end
    resources :items
  end 

  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "callbacks" }

  resources :users

  root to: "auctions#home"

end

app/models/auctioneer.rb
class Auctioneer < ActiveRecord::Base
   belongs_to :user
   belongs_to :auction
end

app/controllers/auctioneers_controller.rb
class AuctioneersController < ApplicationController
  before_action :set_auctioneer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :edit, :update, :new]
  before_action :authenticate_admin!, only: [:index, :destroy]
  before_action :authenticate_auctioneer!, only: [:edit, :update, :new]

  # GET /auctioneers
  # GET /auctioneers.json
  def index
    if current_user.is_admin
      @auctioneers = Auctioneer.all
    else
      flash[:notice] = "You must be an admin to access that link."
    end
  end

  # GET /auctioneers/1
  # GET /auctioneers/1.json
  def show
  end

  # GET /auctioneers/new
  def new
    @auctioneer = Auctioneer.new
  end

  # GET /auctioneers/1/edit
  def edit
  end

  # POST /auctioneers
  # POST /auctioneers.json
  def create
    @auctioneer = Auctioneer.new(auctioneer_params)
    #@auctioneer = current_user.auctioneers.build(:auction_id => params[:auction_id])
    respond_to do |format|
      if @auctioneer.save
        format.html { redirect_to @auctioneer, notice: 'Auctioneer was successfully created.' }
        format.json { render :show, status: :created, location: @auctioneer }
      else
        format.html { render :new }
        format.json { render json: @auctioneer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auctioneers/1
  # PATCH/PUT /auctioneers/1.json
  def update
    respond_to do |format|
      if @auctioneer.update(auctioneer_params)
        format.html { redirect_to @auctioneer, notice: 'Auctioneer was successfully updated.' }
        format.json { render :show, status: :ok, location: @auctioneer }
      else
        format.html { render :edit }
        format.json { render json: @auctioneer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auctioneers/1
  # DELETE /auctioneers/1.json
  def destroy
    @auctioneer.destroy
    respond_to do |format|
      format.html { redirect_to auctioneers_url, notice: 'Auctioneer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auctioneer
      @auctioneer = Auctioneer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auctioneer_params
      params.require(:auctioneer).permit(:user_id, :auction_id, :create, :destroy)
    end
end

app/helpers/auctioneers_helper.rb
module AuctioneersHelper
end

app/views/auctioneers/_form.html.erb
<%= form_for(@auctioneer) do |f| %>
  <% if @auctioneer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auctioneer.errors.count, "error") %> prohibited this auctioneer from being saved:</h2>

      <ul>
      <% @auctioneer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.collection_select(:user_id, User.all, :id, :email) %>
  </div>
  <div class="field">
   <%= f.collection_select(:auction_id, Auction.all, :id, :title) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/auctioneers/edit.html.erb
<h1>Editing auctioneer</h1>

<%= render 'form' %>

<%= link_to 'Show', @auctioneer %> |
<%= link_to 'Back', auctioneers_path %>

app/views/auctioneers/index.html.erb
<h1>Listing auctioneers</h1>

<table>
  <thead>
    <tr>
      <th>Auctioneer</th>
      <th>Auction</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auctioneers.each do |auctioneer| %>
      <% fullname = auctioneer.user.first_name + ' ' + auctioneer.user.last_name%>
      <tr>
        <td><%= fullname %></td>
        <td><%= auctioneer.auction.title %></td>
        <td><%= link_to 'Show', auctioneer %></td>
        <td><%= link_to 'Edit', edit_auctioneer_path(auctioneer) %></td>
        <td><%= link_to 'Destroy', auctioneer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Auctioneer', new_auctioneer_path %>

app/views/auctioneers/new.html.erb
<h1>New auctioneer</h1>

<%= render 'form' %>

<%= link_to 'Back', auctioneers_path %>

app/views/auctioneers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @auctioneer.user_id %>
</p>

<p>
  <strong>Auction:</strong>
  <%= @auctioneer.auction_id %>
</p>

<%= link_to 'Edit', edit_auctioneer_path(@auctioneer) %> |
<%= link_to 'Back', auctioneers_path %>