config/routes.rb
Rails.application.routes.draw do

  get 'auctions_users/create'

  get 'auctions_users/destroy'

  get 'auctions/myauctions'

  resources :auctioneers

  resources :bids

  resources :items do
    member do
      get 'newbid'
    end
    resources :bids
    end 

  resources :auctions do
    member do
      get 'auction_items'
      get 'finalize'
    end
    resources :items
  end 

  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "callbacks" }

  resources :users

  root to: "auctions#home"

end

app/models/auction.rb
class Auction < ActiveRecord::Base
   has_many :items
   has_many :bids, through: :items
   has_many :auctioneers
   has_many :users, through: :auctioneers 
   accepts_nested_attributes_for :items, :bids

has_attached_file :logo, 
:path => ":rails_root/public/system/:attachment/:id/:basename_:style.:extension",
:url => "/system/:attachment/:id/:basename_:style.:extension",
:styles => {
  :thumb    => ['100x100#',  :jpg, :quality => 70],
  :logo1    => ['200x100#',  :jpg, :quality => 70],
  :logo2    => ['150x100#',  :jpg, :quality => 70],
  :preview  => ['480x480#',  :jpg, :quality => 70],
  :large    => ['600x',      :jpg, :quality => 70],
  :auction1 => ['x700',      :jpg, :quality => 70],
  :larger   => ['x600',      :jpg, :quality => 70],
  :retina   => ['1200>',     :jpg, :quality => 30]
},
:convert_options => {
  :thumb    => '-set colorspace sRGB -strip',
  :logo1    => '-set colorspace sRGB -strip',
  :logo2    => '-set colorspace sRGB -strip',
  :preview  => '-set colorspace sRGB -strip',
  :large    => '-set colorspace sRGB -strip',
  :auction1 => '-set colorspace sRGB -strip',
  :larger   => '-set colorspace sRGB -strip',
  :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'
}
validates_attachment :logo,
    :presence => true,
    :size => { :in => 0..20.megabytes },
    :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }
  def running?
    self.start_date < Date.today && self.end_date >= Date.today
  end
 def auctioneer 
   owner = Auctioneer.where(auction_id: self.id)
   auctioneer = User.find(owner)
 end
 def tally
   tally = 0
   @items = self.items.all
   @items.each do |i|
     if !i.bids.last.blank?
       if i.buyitnow
         i.bids.each do |b|
           tally += b.amount * b.qty
         end
       else
         tally += i.bids.last.amount
       end
     end
   end
   return tally
 end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :new, :destroy, :index]
  before_action :set_auction, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_auctioneer!, only: [:edit, :update, :new]
  before_action :authenticate_admin!, only: [:destroy]

  # GET /auctions
  # GET /auctions.json
  def home
  end
  def index
    if user_signed_in? 
      @owner = owner
    end
    if (current_user.is_admin || current_user.is_auctioneer)
      @auctions = Auction.all
    else
      @auctions = Auction.where(display: true)
    end 
  end

  # GET /auctions/1
  # GET /auctions/1.json
  def show
    if user_signed_in? 
    @owner = owner 
    end
  end

  def finalize 
    @auction = Auction.find(params[:id])
    respond_to do |format|
    @auction.display = false
      if @auction.save
        items = Item.where(auction_id: @auction.id)
        winners = []
        items.each do |i|
          winners << i.highbidder
        end
        winners = winners.uniq
        winners.each do |w|
          wonitems = []
          items.each do |it| 
           if it.highbidder == w
             wonitems << it
           end
          end 
          UserMailer.won_item(@auction, wonitems, w.email)
        end
        format.html { redirect_to @auction, notice: 'Auction was successfully finalized and emails sent.' }
        format.json { render :show, status: :created, location: @auction }
      else
        format.html { render :new }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # GET /auctions/new
  def new
    @auction = Auction.new
    @auction.items.build
  end

  # GET /auctions/1/edit
  def edit
    if user_signed_in? 
      @owner = owner 
    end
  end

  def auction_items
    @auction = Auction.find(params[:id])
    @items = @auction.items.all.order(seq: :asc)
    if user_signed_in? 
      @owner = owner 
    end
  end 

  # POST /auctions
  # POST /auctions.json
  def create
    @auction = Auction.new(auction_params)
    @auctioneer = @auction.auctioneers.build 
    @auctioneer.user_id = current_user.id
    respond_to do |format|
      if @auction.save && @auctioneer.save
        Notifier.welcome(current_user.email).deliver
        format.html { redirect_to @auction, notice: 'Auction was successfully created.' }
        format.json { render :show, status: :created, location: @auction }
      else
        format.html { render :new }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auctions/1
  # PATCH/PUT /auctions/1.json
  def update
    respond_to do |format|
      if @auction.update(auction_params)
        format.html { redirect_to @auction, notice: 'Auction was successfully updated.' }
        format.json { render :show, status: :ok, location: @auction }
      else
        format.html { render :edit }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  def enter
      @auction = Auction.find(params[:id])
      @fullname = @auction.auctioneers.first.user.first_name + ' ' + @auction.auctioneers.first.user.last_name
  end

  # DELETE /auctions/1
  # DELETE /auctions/1.json
  def destroy
    @auction.destroy
    respond_to do |format|
      format.html { redirect_to auctions_url, notice: 'Auction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def owner
     if @auction
       return @auction.auctioneers.detect { |o| o["user_id"] == current_user.id }
     else return 0
     end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auction
      @auction = Auction.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def auction_params
      params.require(:auction).permit(:id, :title, :description, :start_date, :end_date, :display, :winner_message, :logo, :finalized, :payment, items_attributes:[:id, :title, :description, :start_bid, :bid_increment, :auction_id, :is_donation, :buyitnow, :picture, :picture_file_name, :picture_contnet_type, :picture_file_size, :picture_updated_at, :qty, :seq, :value], bids_attributes:[:id, :user_id, :item_id, :amount, :created_at, :updated_at, :qty] )
    end
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/views/auctions/_bid_fields.html.erb
   <fieldset>
     <%= f.label :Bid %>
     <%= f.text_field :amount %><br>
   </fieldset>

app/views/auctions/_enter_auction.html.erb
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Buyitnow</th>
      <th>Quantity</th>
      <th>Start bid</th>
      <th>Bid increment</th>
      <th>Auction</th>
      <th>Is donation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.description %></td>
        <td><%= item.buyitnow %></td>
        <td><%= item.qty %></td>
        <td><%= item.start_bid %></td>
        <td><%= item.bid_increment %></td>
        <td><%= item.auction_id %></td>
        <td><%= item.is_donation %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path(@items.first.auction_id) %>

app/views/auctions/_finalize.html.erb
<%= form_for(@auction) do |f| %>
  <% if @auction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auction.errors.count, "error") %> prohibited this auction from being saved:</h2>

      <ul>
      <% @auction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
   <%= f.label :finalized, "Finalize!" %><br>
     <%= f.check_box :finalized %> <br>
     </div>
  <div class="actions">
    <%= f.submit "Finalize!", data: {confirm: "Are you sure you want to Finalize this auction?"} %>
  </div>
<% end %>

app/views/auctions/_form.html.erb
<%= form_for(@auction) do |f| %>
  <% if @auction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auction.errors.count, "error") %> prohibited this auction from being saved:</h2>

      <ul>
      <% @auction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
   <%= f.label :auctioneers %><br>
   <% @auction.users.each do |auctioneer| %>
     <% fullname =  auctioneer.first_name + ' ' +  auctioneer.last_name %>
     <%= fullname %> <%= auctioneer.email %> <br>
  <% end %>
     </div>
    <center><%= image_tag @auction.logo.url(:logo) %></center>
  <div class="field">
    <%= f.label :logo %><br>
    <%= f.file_field :logo %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :payment, "Payment Methods" %><br>
    <%= f.text_area :payment %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :display %><br>
    <%= f.check_box :display %>
  </div>
  <div class="field">
    <%= f.label :winner_message %><br>
    <%= f.text_area :winner_message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <%= f.fields_for :items do |builder| %>
   <% render 'item_fields', f: builder %>
   <% end %>
   <%= link_to_add_fields "Add Item", f, :items %>
<% end %>

app/views/auctions/_item_fields.html.erb
   <fieldset>
     <%= f.label :title, "Item" %>
     <%= f.text_area :title %><br>
     <%= f.label :seq, "Order" %>
     <%= f.number_field :seq %><br>
     <%= f.label :picture %>
     <%= f.file_field :picture %><br>
     <%= f.label :description %>
     <%= f.text_area :description %><br>
     <%= f.check_box :buyitnow %>
     <%= f.label :buyitnow, "Buy it now : " %>
     <%= f.label :qty, "Quantity" %>
     <%= f.number_field :qty %><br>
     <%= f.check_box :is_donation %>
     <%= f.label :is_donation, "Is a Donation" %><br>
     <%= f.label :value %>
     <%= f.text_field :value %>
     <%= f.label :start_bid %>
     <%= f.text_field :start_bid %>
     <%= f.label :bid_increment %>
     <%= f.text_field :bid_increment %>
   </fieldset>
  <div class="actions">
    <%= f.submit %>
  </div>

app/views/auctions/auction_items.html.erb
<%if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
<h1>Listing items for auction: <%= @auction.title %></h1>

<table>
  <thead>
    <tr>
      <th><strong>Picture:</strong></th>
      <th>Title</th>
      <th>Description</th>
      <th>Buy it now</th>
      <th>Quantity available</th>
      <th>Estimated value</th>
      <th>Start bid</th>
      <th>Bid increment</th>
      <th>Current high bid</th>
      <th>High bidder</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= image_tag item.picture.url(:logo2) %></td>
        <td><%= item.title %></td>
        <td><%= item.description %></td>
        <td><%= item.buyitnow %></td>
        <td><%= item.qty %></td>
        <td><%= number_to_currency(item.value) %></td>
        <td><%= number_to_currency(item.start_bid) %></td>
        <td><%= number_to_currency(item.bid_increment) || "N/A"%></td>
        <td><%= number_to_currency(item.bids.maximum(:amount)) || number_to_currency(0) %></td>
        <% if current_user == item.highbidder %>
           <% if item.buyitnow %>
            <td>I purchased one or more </td>
           <% else %>
            <td>I am high bidder </td>
           <% end %>
        <% else %>
            <td>I am NOT high bidder! </td>
        <% end %>
        <% if DateTime.now > @auction.start_date && DateTime.now < @auction.end_date %>
        <% if item.buyitnow  %>
            <% if item.qty > 0 %>
              <td><%= link_to 'Buy this item now', new_bid_path(item: item.id) %></td>
            <% else %>
              <td>SOLD OUT</td>
            <% end %>
        <% else %>
          <% if item.is_donation %><td><%= link_to 'Make a donation', new_bid_path(item: item.id) %></td>
           <% else %><td><%= link_to 'Bid on this item', new_bid_path(item: item.id) %></td><% end %>
           <% end %>
        <% if @owner %>
          <td><%= link_to 'Edit', edit_item_path(item, auction: item.auction_id) %></td>
          <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if @owner %>
  <%= link_to 'New Item', new_item_path(auction: @auction.id) %>
<% end %>
<%= link_to 'Back', auctions_path %>

app/views/auctions/edit.html.erb
<h1>Editing auction</h1>

<%= render 'form' %>

<%= link_to 'Show', @auction %> |
<%= link_to 'Back', auctions_path %>

app/views/auctions/enter.html.erb
<BODY
  BGCOLOR="#FFFFFF"
  TEXT="#000000"
  LINK="#0000FF"
  VLINK="#FF66FF"
  ALINK="#FF0000"
  >                      

<h1><center><%= @auction.title %></center></h1>


<table>
  <tr>
    <th>Title </th>
    <th>Benefit Description </th>
    <th>Start date</th>
    <th>End date</th>
    <th>Contact name</th>
    <th>Contact email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <tr>
    <td><%= @auction.title %> </td>
    <td><%= @auction.description %>  </td>
    <td><%= @auction.start_date %>  </td>
    <td><%= @auction.end_date %>  </td>
    <td><%= @fullname%></td>
    <td><%= @auction.auctioneers.first.user.email %>  </td>
  </tr>
</table>

<br />

<table>
  <tr>
    <th></th>
    <th>Item Name</th>
    <th>Description</th>
    <th>Start bid</th>
    <th>High bid</th>
  </tr>

<% @auction.items.each do |item| %>
  <tr>
    <td>
      <%if item.photo.exists? then  %>
        <%= image_tag item.photo.url(:small) %>
      <% end %>
        </td>
    <td><%= item.name %></td>
    <td><%= item.description %></td>
    <td>$<%= item.start_bid %></td>
    <td>$<%= item.bids.maximum("amount") || "0" %></td>
    <td><%= link_to 'place bid', new_bid_path(:item_id => item) %></td>
 </tr>
<% end %>
</table>

<br />

app/views/auctions/finalize.html.erb
<p id="notice"><%= notice %></p>

<p>
    <center><%= image_tag @auction.logo.url(:large) %></center>
</p>
<p>
  <strong>FINALIZE! Auction:</strong>
  <%= @auction.title %>
</p>
<p>
  <strong>Auctioneers:</strong>
  <% @auction.auctioneers.each do |auctioneer| %>
  <% fullname = auctioneer.user.first_name + ' ' + auctioneer.user.last_name%>
  <%= fullname  %>,
  <% end %></td>
</p>
<p>
  <strong>Description:</strong>
  <%= @auction.description %>
</p>
<p>
  <strong>Payment Methods:</strong>
  <%= @auction.payment %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @auction.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @auction.end_date %>
</p>

<p>
  <strong>Display:</strong>
  <%= @auction.display %>
</p>
<h1>Finalize auction</h1>

<%= render 'finalize' %>

<%= link_to 'Show', @auction %> |
<%= link_to 'Back', auctions_path %>

app/views/auctions/home.html.erb
<%if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>
<p><center><h2>Welcome to the Auctions home page</center>

The purpose of this auction site is to provide a means for non-profit organizations to raise money for their projects. To view available auctions click the Auctions link on the left.
<br><br><br><br>
<br><br><br><br>
<br><br><br><br>

app/views/auctions/index.html.erb
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>
<h1>List of currently running auctions</h1>
<table>
  <thead>
    <tr>
      <th>Auction Sponsor</th>
      <th>Auctioneers</th>
      <th>Title</th>
      <th>Description</th>
      <th>Start date</th>
      <th>End date</th>
      <% if current_user.is_auctioneer %>
        <th>Enabled</th>
        <th>Tally</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @auctions.each do |auction| %>
      <% if DateTime.now > auction.start_date && DateTime.now < auction.end_date || @owner %>
      <tr>
        <td><%= image_tag auction.logo.url(:logo1) %></td>
        <td>
        <% auction.auctioneers.each do |auctioneer| %>
        <% fullname = auctioneer.user.first_name + ' ' + auctioneer.user.last_name%>
        <%= fullname  %><br>
        <% end %></td>
        <td><%= auction.title %></td>
        <td><%= auction.description %></td>
        <td><%= auction.start_date %></td>
        <td><%= auction.end_date %></td>
        <% if current_user.is_auctioneer %>
          <td><%= auction.display %></td>
          <td><%= auction.tally %></td>
        <% end %>
        <% if auction.display %><td><%= link_to 'Enter Auction', auction %></td><% end %>
        <% if user_signed_in? %>
          <% if current_user.is_auctioneer %><td><%= link_to 'Edit', edit_auction_path(auction) %></td><% end %>
          <% if current_user.is_auctioneer %><td><%= link_to 'Destroy', auction, method: :delete, data: { confirm: 'Are you sure?' } %></td><% end %>
        <% end %>
       </tr>
       <% end %>
       <% end %>
  </tbody>
</table>
<%= link_to 'Back', :back %>
<br>
<br>
<br>
<br>
<br>

app/views/auctions/new.html.erb
<h1>New auction</h1>

<%= render 'form' %>

<%= link_to 'Back', auctions_path %>

app/views/auctions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <center><%= image_tag @auction.logo.url(:large) %></center>
</p>
<p>
  <strong>Auction:</strong>
  <%= @auction.title %>
</p>
<p>
  <strong>Auctioneers:</strong>
  <% @auction.auctioneers.each do |auctioneer| %>
  <% fullname = auctioneer.user.first_name + ' ' + auctioneer.user.last_name%>
  <%= fullname  %>,
  <% end %></td>
</p>
<p>
  <strong>Description:</strong>
  <%= @auction.description %>
</p>
<p>
  <strong>Payment Methods:</strong>
  <%= @auction.payment %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @auction.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @auction.end_date %>
</p>

<% if @owner %><%= link_to 'Edit', edit_auction_path(@auction) %><% end %> 
<% if @owner && @auction.display %><%= link_to 'Finalize', finalize_auction_path(@auction) %><% end %> 
<%= link_to 'View Items', auction_items_auction_path(@auction) %> 
<%= link_to 'Back', auctions_path %>