config/routes.rb
Rails.application.routes.draw do

  get 'auctions_users/create'

  get 'auctions_users/destroy'

  get 'auctions/myauctions'

  resources :auctioneers

  resources :bids

  resources :items do
    member do
      get 'newbid'
    end
    resources :bids
    end 

  resources :auctions do
    member do
      get 'auction_items'
      get 'finalize'
    end
    resources :items
  end 

  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "callbacks" }

  resources :users

  root to: "auctions#home"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auctions</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
<body id="auctions">
  <div id="banner">
    <h2><center><%= @page_title || "Auctions Web Site" %></center></h2>
</center>
<%if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
 <div id="columns">
    <div id="side">
      <%= link_to "Home", root_path %><br>
      <%= link_to "Auctions", auctions_path %><br>
      <hr>
      <% if user_signed_in? && current_user.is_auctioneer %>
      <font color="#ff0000">Auctioneers only</font><br> 
      <%= link_to "New Auction", new_auction_path %><br>
      <%= link_to "Items List", items_path %><br>
      <%= link_to "Bids List", bids_path %><br>
      <% end %>
      <hr>
      <% if user_signed_in? && current_user.is_admin %>
      <font color="#ff0000">Admins only</font><br>
      <%= link_to "Auctioneers List", auctioneers_path %><br>
      <%= link_to "Users List", users_path %><br>
      <% end %>
    </div>
   <div id="main">
     <%= yield %>
   </div>
 </div>
</body>
</html>